_target_: src.models.process_model.ProcessModel

model_name: ${model_name}
embedding_layer: 'last'
mode: 'sentence'
 
learning_rate: 5e-5
weight_decay: 0.0
adam_eps: 1e-8
warmup_steps: 0

loss_alpha: 0.2
loss_beta: 0.8
